name: CI

on:
  push:
#    tags:
#      - '*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM 17
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt-get update
        sudo apt-get install -y llvm-17-dev clang-17

    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM with winget
      run: |
        # Устанавливаем LLVM с помощью winget
        winget install -e --id LLVM.LLVM --version 17.0.6

    - name: Find LLVM installation path
      run: |
        # Ищем путь установки LLVM
        $llvmPath = (Get-ItemProperty -Path "HKLM:\SOFTWARE\LLVM\LLVM" -ErrorAction SilentlyContinue).'(default)'
        if (-not $llvmPath) {
          $llvmPath = "C:\Program Files\LLVM"
        }
        echo "LLVM_PATH=$llvmPath" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "LLVM_DIR=$llvmPath\lib\cmake\llvm" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Verify LLVM installation
      run: |
        Write-Host "LLVM installation verification:"
        Write-Host "LLVM_PATH: $env:LLVM_PATH"
        Write-Host "LLVM_DIR: $env:LLVM_DIR"
        
        # Проверяем существование ключевых файлов
        if (Test-Path "$env:LLVM_DIR") {
          Write-Host "LLVM CMake directory exists"
          Get-ChildItem "$env:LLVM_DIR" | ForEach-Object { Write-Host "  - $($_.Name)" }
        } else {
          Write-Host "LLVM CMake directory does not exist"
          # Попробуем найти CMake файлы в других местах
          $foundCmake = Get-ChildItem -Path "$env:LLVM_PATH" -Recurse -Filter "*config.cmake" | Select-Object -First 1
          if ($foundCmake) {
            $newLlvmDir = $foundCmake.Directory.FullName
            Write-Host "Found LLVM CMake files at: $newLlvmDir"
            echo "LLVM_DIR=$newLlvmDir" | Out-File -FilePath $env:GITHUB_ENV -Append
          }
        }

    - name: Add LLVM to PATH
      run: echo "$env:LLVM_PATH\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake with explicit paths
      run: |
        # Явно указываем пути к LLVM
        cmake -B build `
          -DCMAKE_BUILD_TYPE=Release `
          -G "Visual Studio 17 2022" `
          -DLLVM_DIR="$env:LLVM_DIR" `
          -DCMAKE_PREFIX_PATH="$env:LLVM_PATH"

    - name: Build
      run: cmake --build build --config Release